/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import BDD.BDDConnexion;
import Main.Main;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author lambda
 */
public class FenetreSelectionCours extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    String getGroupeChoisi() {
        return this.groupeChoisi;
    }

    private JPanel contentPane;
    private ArrayList<String> listePromo = new ArrayList<String>();
    private ArrayList<String> listeGroupes = new ArrayList<String>();
    private ArrayList<String> listeMatieres = new ArrayList<String>();
    private ArrayList<String> listeCoursMyfare = new ArrayList<String>();
    
    private static String promoChoisie = "";
    private static String groupeChoisi = "";
    private static String matiereChoisie = "";
    private static String matiereMyFare  = "";
    
    
    
    
    String getMatiereChoisie() {
        return this.matiereChoisie;
    }
    
    
    
    /**
     * Creates new form FrameSelectionCours
     */
    public FenetreSelectionCours() {
        this.setLocation(300, 200);
        initComponents();
	listePromo.add("                ");
        listePromo.add("Ei1");
        listePromo.add("Ei2");
        listePromo.add("Ei3");
	// Liste des groupes
	listeGroupes.add("                ");
	// Liste des matières
	listeMatieres.add("                ");
        listeCoursMyfare.add("                ");
        remplirComboPromo();
        remplirComboGroupe();
        remplirComboMatiere();
        remplirComboCoursMyFare();
        jcPromo.addActionListener(new PromoAction());
        
        jcGroupe.addActionListener(new GroupeAction());
        this.jTextMyFare.requestFocus();
    }
    
    /**
     * La liste des groupes est initialisée selon l'item selectionné de la liste déroulante des promotions
     * @param args the command line arguments
     */
    class PromoAction implements ActionListener {
        public void actionPerformed(ActionEvent e) {
        	promoChoisie = (String) jcPromo.getSelectedItem();
        	listeGroupes = BDDConnexion.listeGroupes(promoChoisie);
        	remplirComboGroupe();
        }
    }
    
    /**
     * La liste des matières est initialisée selon les items selectionnés dans la liste déroulante des promotions et celle des groupes
     * @param args the command line arguments
     */
    class GroupeAction implements ActionListener {
        public void actionPerformed(ActionEvent e) {
        	promoChoisie = (String) jcPromo.getSelectedItem();
        	groupeChoisi = (String) jcGroupe.getSelectedItem();
        	listeMatieres = BDDConnexion.listeMatieres(promoChoisie, groupeChoisi);
        	remplirComboMatiere();
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jcPromo = new javax.swing.JComboBox();
        jcGroupe = new javax.swing.JComboBox();
        jcMatiere = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jComboCoursMyFare = new javax.swing.JComboBox();
        jTextMyFare = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sélection de Cours");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sélection de cours"));

        jLabel1.setText("Sélectionnez la promotion:");

        jLabel2.setText("Sélectionnez le groupe:");

        jLabel3.setText("Cours:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcMatiere, 0, 181, Short.MAX_VALUE)
                    .addComponent(jcGroupe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcPromo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcPromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcGroupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcMatiere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Retour");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Sélection avec myFare"));

        jTextMyFare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMyFareActionPerformed(evt);
            }
        });
        jTextMyFare.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextMyFareKeyPressed(evt);
            }
        });

        jLabel4.setText("Numéro myFare:");

        jLabel5.setText("Cours:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextMyFare, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jComboCoursMyFare, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextMyFare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboCoursMyFare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		promoChoisie = (String) jcPromo.getSelectedItem();
		groupeChoisi = (String) jcGroupe.getSelectedItem();
		matiereChoisie = (String) jcMatiere.getSelectedItem();
                matiereMyFare = (String) jComboCoursMyFare.getSelectedItem();
                
		if(jcPromo.getSelectedIndex() > 0  &&
                   jcGroupe.getSelectedIndex() > 0 &&
                   jcMatiere.getSelectedIndex() > 0)
                {
                    int cours_id = BDDConnexion.coursID(promoChoisie, groupeChoisi, matiereChoisie);
                    Main.fenetreControle.setCours_id(cours_id);
                    // On affiche la fenêtre de contrôle, on masque la fenêtre de séléction du cours
                    Main.fenetreSelectionCours.setVisible(false);
                    Main.fenetreControle.majFenetre();
                    Main.fenetreControle.setVisible(true);
                    Main.fenetreControle.textFocus();
                }
                else if(jComboCoursMyFare.getSelectedIndex() > 0)
                {
                    int cours_id = BDDConnexion.coursID(jTextMyFare.getText(), matiereMyFare);
                    Main.fenetreControle.setCours_id(cours_id);
                    // On affiche la fenêtre de contrôle, on masque la fenêtre de séléction du cours
                    Main.fenetreSelectionCours.setVisible(false);
                    Main.fenetreControle.majFenetre();
                    Main.fenetreControle.setVisible(true);
                    Main.fenetreControle.textFocus();
                }else{
                    JOptionPane.showMessageDialog(null, "C'est necessaire de choisir la matière!", "Erreur", JOptionPane.INFORMATION_MESSAGE);
                }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
	Main.fenetreSelectionCours.setVisible(false);
	Main.fenetreAccueil.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextMyFareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMyFareActionPerformed

    }//GEN-LAST:event_jTextMyFareActionPerformed

    private void jTextMyFareKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextMyFareKeyPressed
        String codeMyFare;
        if(java.awt.event.KeyEvent.VK_ENTER == evt.getKeyCode()){
            codeMyFare = jTextMyFare.getText();
            listeCoursMyfare = BDDConnexion.listeCoursEnseignant(codeMyFare);
            remplirComboCoursMyFare();
        }
    }//GEN-LAST:event_jTextMyFareKeyPressed

    	public void remplirComboPromo() {
            for(String s : listePromo) {
            	jcPromo.addItem(s);
            }
	}
	
        public void remplirComboCoursMyFare(){
            for(String s : listeCoursMyfare){
                jComboCoursMyFare.addItem(s);
            }
        }
        
	public void remplirComboMatiere() {
            for(String s : listeMatieres) {
            	jcMatiere.addItem(s);
            }
	}
	
	public void remplirComboGroupe() {
            for(String s : listeGroupes) {
            	jcGroupe.addItem(s);
            }
	}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreSelectionCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreSelectionCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreSelectionCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreSelectionCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FenetreSelectionCours().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboCoursMyFare;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextMyFare;
    private javax.swing.JComboBox jcGroupe;
    private javax.swing.JComboBox jcMatiere;
    private javax.swing.JComboBox jcPromo;
    // End of variables declaration//GEN-END:variables
}
